export const NEW_NOTICE_REQUEST = 'NEW_NOTICE_REQUEST';
export const NEW_NOTICE_SUCCESS = 'NEW_NOTICE_SUCCESS';
export const NEW_NOTICE_FAIL = 'NEW_NOTICE_FAIL';

export const ALL_NOTICE_REQUEST = 'ALL_NOTICE_REQUEST';
export const ALL_NOTICE_SUCCESS = 'ALL_NOTICE_SUCCESS';
export const ALL_NOTICE_FAIL = 'ALL_NOTICE_FAIL';
