export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_FORGETPASSWORD_REQUEST = 'USER_FORGETPASSWORD_REQUEST';
export const USER_FORGETPASSWORD_SUCCESS = 'USER_FORGETPASSWORD_SUCCESS';
export const USER_FORGETPASSWORD_FAIL = 'USER_FORGETPASSWORD_FAIL';

export const USER_NEW_PASSWORD_REQUEST = 'USER_NEW_PASSWORD_REQUEST';
export const USER_NEW_PASSWORD_SUCCESS = 'USER_NEW_PASSWORD_SUCCESS';
export const USER_NEW_PASSWORD_FAIL = 'USER_NEW_PASSWORD_FAIL';

export const NEW_EMPLOYEE_REQUEST = 'NEW_EMPLOYEE_REQUEST';
export const NEW_EMPLOYEE_SUCCESS = 'NEW_EMPLOYEE_SUCCESS';
export const NEW_EMPLOYEE_FAIL = 'NEW_EMPLOYEE_FAIL';

export const NEW_EMPLOYEE_META_REQUEST = 'NEW_EMPLOYEE_META_REQUEST';
export const NEW_EMPLOYEE_META_SUCCESS = 'NEW_EMPLOYE_METAE_SUCCESS';
export const NEW_EMPLOYEE_META_FAIL = 'NEW_EMPLOYEE_META_FAIL';

export const ALL_EMPLOYEE_BY_COMPANYID_REQUEST =
  'ALL_EMPLOYEE_BY_COMPANYID_REQUEST';
export const ALL_EMPLOYEE_BY_COMPANYID_SUCCESS =
  'ALL_EMPLOYEE_BY_COMPANYID_SUCCESS';
export const ALL_EMPLOYEE_BY_COMPANYID_FAIL = 'ALL_EMPLOYEE_BY_COMPANYID_FAIL';

export const EMPLOYEE_REMOVE_REQUEST = 'EMPLOYEE_REMOVE_REQUEST';
export const EMPLOYEE_REMOVE_SUCCESS = 'EMPLOYEE_REMOVE_SUCCESS';
export const EMPLOYEE_REMOVE_FAIL = 'EMPLOYEE_REMOVE_FAIL';

export const STUDENT_ATTENDANCE_GET_REQUEST = 'STUDENT_ATTENDANCE_GET_REQUEST';
export const STUDENT_ATTENDANCE_GET_SUCCESS = 'STUDENT_ATTENDANCE_GET_SUCCESS';
export const STUDENT_ATTENDANCE_GET_FAIL = 'STUDENT_ATTENDANCE_GET_FAIL';

export const STUDENT_ATTENDANCE_POST_REQUEST =
  'STUDENT_ATTENDANCE_POST_REQUEST';
export const STUDENT_ATTENDANCE_POST_SUCCESS =
  'STUDENT_ATTENDANCE_POST_SUCCESS';
export const STUDENT_ATTENDANCE_POST_FAIL = 'STUDENT_ATTENDANCE_POST_FAIL';
